In [3]:
Contents for Theory: 
1. Summary statistics 
2. Types of Variables 
3. Summary statistics of income grouped by the age groups 
4. Display basic statistical details on the iris dataset.

NameError: name 'df_iris' is not defined

In [4]:
import seaborn as sns
import pandas as pd
from sklearn import preprocessing
df = sns.load_dataset("iris")
summary_stats = df_iris.describe()
print(summary_stats)

NameError: name 'df_iris' is not defined

In [5]:
mean_values = df_iris.select_dtypes(include='number').mean()
print(mean_values)

NameError: name 'df_iris' is not defined

In [6]:
mean_sepal_length = df.loc[:, 'sepal_length'].mean()
print(mean_sepal_length)

5.843333333333334

In [7]:
mean_values_row_wise = df.select_dtypes(include=['number']).mean(axis=1)[0:4]
print(mean_values_row_wise)

0    2.550
1    2.375
2    2.350
3    2.350
dtype: float64

In [8]:
median_values = df.select_dtypes(include=['number']).median()
print(median_values)

sepal_length    5.80
sepal_width     3.00
petal_length    4.35
petal_width     1.30
dtype: float64

In [9]:
df.loc[:,'sepal_length'].median()

5.8

In [10]:
numeric_df = df.iloc[:, :-1]  
medians = numeric_df.median(axis=1)
print(medians[0:4])

0    2.45
1    2.20
2    2.25
3    2.30
dtype: float64

In [11]:
df.loc[:,'sepal_length'].mode()

0    5.0
Name: sepal_length, dtype: float64

In [12]:
df.min()

sepal_length       4.3
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

In [13]:
df.loc[:,'sepal_length'].min(skipna = False)

4.3

In [14]:
df.max()

sepal_length          7.9
sepal_width           4.4
petal_length          6.9
petal_width           2.5
species         virginica
dtype: object

In [15]:
df.loc[:,'sepal_length'].max(skipna = False)

7.9

In [16]:
df_numeric = df.select_dtypes(include='number')
df_numeric.std()

sepal_length    0.828066
sepal_width     0.435866
petal_length    1.765298
petal_width     0.762238
dtype: float64

In [17]:
df.loc[:,'sepal_length'].std()

0.8280661279778629

In [18]:
df.groupby(['sepal_length'])['sepal_width'].mean()

sepal_length
4.3    3.000000
4.4    3.033333
4.5    2.300000
4.6    3.325000
4.7    3.200000
4.8    3.180000
4.9    2.950000
5.0    3.120000
5.1    3.477778
5.2    3.425000
5.3    3.700000
5.4    3.550000
5.5    2.842857
5.6    2.816667
5.7    3.100000
5.8    2.885714
5.9    3.066667
6.0    2.733333
6.1    2.850000
6.2    2.825000
6.3    2.855556
6.4    2.957143
6.5    3.000000
6.6    2.950000
6.7    3.050000
6.8    3.000000
6.9    3.125000
7.0    3.200000
7.1    3.000000
7.2    3.266667
7.3    2.900000
7.4    2.800000
7.6    3.000000
7.7    3.050000
7.9    3.800000
Name: sepal_width, dtype: float64

In [19]:
df.groupby(['sepal_length'])['petal_length'].mean()

sepal_length
4.3    1.100000
4.4    1.333333
4.5    1.300000
4.6    1.325000
4.7    1.450000
4.8    1.580000
4.9    2.266667
5.0    1.840000
5.1    1.722222
5.2    2.075000
5.3    1.500000
5.4    2.033333
5.5    3.228571
5.6    4.200000
5.7    3.587500
5.8    4.071429
5.9    4.700000
6.0    4.650000
6.1    4.750000
6.2    4.750000
6.3    5.133333
6.4    5.157143
6.5    5.240000
6.6    4.500000
6.7    5.262500
6.8    5.400000
6.9    5.275000
7.0    4.700000
7.1    5.900000
7.2    5.966667
7.3    6.300000
7.4    6.100000
7.6    6.600000
7.7    6.600000
7.9    6.400000
Name: petal_length, dtype: float64

In [20]:
enc = preprocessing.OneHotEncoder()
enc_df = pd.DataFrame(enc.fit_transform(df[['petal_length']]).toarray())
enc_df

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
146,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [21]:
df_encode = df.join(enc_df)
df_encode

,sepal_length,sepal_width,petal_length,petal_width,species,0,1,2,3,4,...,33,34,35,36,37,38,39,40,41,42
0,5.1,3.5,1.4,0.2,setosa,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,4.9,3.0,1.4,0.2,setosa,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,4.7,3.2,1.3,0.2,setosa,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,4.6,3.1,1.5,0.2,setosa,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,5.0,3.6,1.4,0.2,setosa,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
146,6.3,2.5,5.0,1.9,virginica,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
147,6.5,3.0,5.2,2.0,virginica,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
148,6.2,3.4,5.4,2.3,virginica,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
149,5.9,3.0,5.1,1.8,virginica,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
iris = pd.read_csv("C:/Users/HP/OneDrive/Desktop/Iris.csv")

In [23]:
irisSet = (iris['Species']== 'Iris-setosa')

In [24]:
print('Iris-setosa') 
print(iris[irisSet].describe())

Iris-setosa
             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

In [25]:
irisVer = (iris['Species']== 'Iris-versicolor')

In [26]:
print('Iris-versicolor') 
print(iris[irisVer].describe())

Iris-versicolor
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

In [27]:

irisVir = (iris['Species']== 'Iris-virginica')

In [28]:
print('Iris-virginica') 
print(iris[irisVir].describe())

Iris-virginica
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000